version: "3.9"

services:
  db:
    image: postgres:16
    container_name: skillforge_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - skillforge_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: skillforge_pgadmin
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  skillforge_db_data:
  pgadmin_data:
